# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Accidental Technologist
email: rbazinet@accidentaltechnologist.com
description: >- # this means to ignore newlines until "baseurl:"
  Musings about Entrepreneurship, Technology and Software Development.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://accidentaltechnologist.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: rbazinet
github_username:  rbazinet
linkedin_username: rbazinet

# SEO Settings
author:
  name: Rob Bazinet
  email: rbazinet@accidentaltechnologist.com
  twitter: rbazinet
  avatar: /assets/img/author-avatar.jpg
  bio: Entrepreneur and software developer sharing insights on technology, startups, and software development.

# Social media and OpenGraph
social:
  name: Rob Bazinet
  links:
    - https://twitter.com/rbazinet
    - https://github.com/rbazinet
    - https://accidentaltechnologist.com

# Default SEO settings
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Rob Bazinet"
# image: /assets/img/default-post-image.svg  # Only uncomment if you want all posts to have a default image
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

# Additional SEO
lang: en_US
locale: en_US
canonical_url: true

# Timezone configuration
timezone: America/New_York

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-compose
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-reading-time

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Google Analytics
google_analytics: G-V8GPSLGQH0

# Comments Configuration
comments:
  utterances:
    repo: rbazinet/accidental_technologist
    theme: github-light
    issue_term: pathname

# Syntax highlighting
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    line_numbers: false

# Sass configuration to suppress deprecation warnings
# These warnings come from the Minima theme itself using deprecated @import syntax
# Will be resolved when theme is updated to use modern Sass @use/@forward
sass:
  style: compressed
  quiet_deps: true
  verbose: false
  silence_deprecations:
    - import
    - color-functions
    - global-builtin

paginate: 10
paginate_path: "/page:num/"

# Reading time configuration
reading_time:
  words_per_minute: 200
  include_seconds: false
      