[build]
  publish = "_site"
  command = "JEKYLL_ENV=production bundle exec jekyll build --config _config.yml,_config_production.yml"

[build.environment]
  JEKYLL_ENV = "production"
  RUBY_VERSION = "3.4.5"

[[redirects]]
  from = "/wp-content/uploads/2012/09/fhpc12.pdf"
  to = "/assets/img/2012/09/fhpc12.pdf"
  status = 301

[[redirects]]
  from = "/wp-content/uploads/2012/11/algorithms.pdf"
  to = "/assets/img/2012/11/algorithms.pdf"
  status = 301

# Force HTTPS for all traffic
[[redirects]]
  from = "http://accidentaltechnologist.com/*"
  to = "https://accidentaltechnologist.com/:splat"
  status = 301
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"