name: Pre-Deploy Validation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate-and-build:
    name: Validate Configuration & Build Site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python for TOML validation
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install validation tools
        run: |
          pip install toml pyyaml

      - name: Validate netlify.toml syntax
        run: |
          echo "🔍 Validating netlify.toml syntax..."
          python -c "
          import toml
          try:
              with open('netlify.toml', 'r') as f:
                  config = toml.load(f)
              print('✅ netlify.toml syntax is valid')
              
              # Additional checks
              if 'redirects' in config:
                  print(f'📋 Found {len(config[\"redirects\"])} redirect rules')
                  
                  # Check for common issues
                  for i, redirect in enumerate(config['redirects']):
                      if 'from' not in redirect or 'to' not in redirect:
                          print(f'❌ Redirect {i+1} missing required fields')
                          exit(1)
                      if not redirect['from'].startswith('/') and not redirect['from'].startswith('http'):
                          print(f'❌ Redirect {i+1} has invalid from pattern: {redirect[\"from\"]}')
                          exit(1)
              else:
                  print('⚠️  No redirects found in netlify.toml')
          except Exception as e:
              print(f'❌ netlify.toml syntax error: {e}')
              exit(1)
          "

      - name: Validate Jekyll config files
        run: |
          echo "🔍 Validating Jekyll configuration..."
          python -c "
          import yaml
          try:
              with open('_config.yml', 'r') as f:
                  config = yaml.safe_load(f)
              print('✅ _config.yml syntax is valid')
              
              # Check for required fields
              required_fields = ['title', 'url', 'baseurl']
              for field in required_fields:
                  if field not in config:
                      print(f'❌ Missing required field: {field}')
                      exit(1)
              
              # Check URL format
              if not config['url'].startswith('https://'):
                  print('❌ URL should use HTTPS')
                  exit(1)
                  
              print(f'🌐 Site URL: {config[\"url\"]}')
              print(f'📝 Site Title: {config[\"title\"]}')
              
          except Exception as e:
              print(f'❌ _config.yml syntax error: {e}')
              exit(1)
          "

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.5'
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Build Jekyll site
        run: |
          echo "🏗️  Building Jekyll site..."
          JEKYLL_ENV=production bundle exec jekyll build --config _config.yml,_config_production.yml
          echo "✅ Jekyll build successful"

      - name: Validate build output
        run: |
          echo "🔍 Validating build output..."
          
          # Check for essential files
          if [ ! -d "_site" ]; then
            echo "❌ _site directory not created"
            exit 1
          fi
          
          if [ ! -f "_site/sitemap.xml" ]; then
            echo "❌ sitemap.xml not generated"
            exit 1
          fi
          
          if [ ! -f "_site/index.html" ]; then
            echo "❌ index.html not generated"
            exit 1
          fi
          
          # Count generated files
          post_count=$(find _site -name "*.html" | wc -l)
          echo "📄 Generated $post_count HTML files"
          
          # Validate sitemap
          python3 -c "
          import xml.etree.ElementTree as ET
          try:
              tree = ET.parse('_site/sitemap.xml')
              root = tree.getroot()
              url_count = len(root)
              print(f'🗺️  Sitemap contains {url_count} URLs')
              
              # Check for HTTPS URLs
              http_count = 0
              for url in root:
                  loc = url.find('{http://www.sitemaps.org/schemas/sitemap/0.9}loc')
                  if loc is not None and loc.text.startswith('http://'):
                      http_count += 1
              
              if http_count > 0:
                  print(f'⚠️  Found {http_count} HTTP URLs in sitemap (should be HTTPS)')
              else:
                  print('✅ All URLs in sitemap use HTTPS')
                  
          except Exception as e:
              print(f'❌ sitemap.xml validation error: {e}')
              exit(1)
          "
          
          echo "✅ Build validation completed"

      - name: Check for common issues
        run: |
          echo "🔍 Checking for common issues..."
          
          # Check for HTTP links in posts
          if grep -r "http://" _posts/ --exclude="*.md~" 2>/dev/null; then
            echo "❌ Found HTTP links in posts (should be HTTPS)"
            echo "Run: find _posts -name '*.md' -exec sed -i 's/http:\/\//https:\/\//g' {} \;"
            exit 1
          else
            echo "✅ No HTTP links found in posts"
          fi
          
          # Check for broken image references
          broken_images=$(find _posts/ -name "*.md" -exec grep -l "!\[.*\](" {} \; | head -3)
          if [ -n "$broken_images" ]; then
            echo "⚠️  Found image references - manual review recommended:"
            echo "$broken_images"
          fi
          
          # Check robots.txt
          if [ -f "robots.txt" ]; then
            echo "✅ robots.txt found"
            if grep -q "Sitemap:" robots.txt; then
              echo "✅ Sitemap reference found in robots.txt"
            else
              echo "⚠️  No sitemap reference in robots.txt"
            fi
          else
            echo "⚠️  robots.txt not found"
          fi
          
          echo "✅ Common issues check completed"

      - name: Summary
        run: |
          echo ""
          echo "🎉 Pre-deploy validation completed successfully!"
          echo "📋 Summary:"
          echo "  ✅ netlify.toml syntax validated"
          echo "  ✅ Jekyll configuration validated"
          echo "  ✅ Site built successfully"
          echo "  ✅ Build artifacts verified"
          echo "  ✅ Common issues checked"
          echo ""
          echo "🚀 Ready for deployment to Netlify!"